### ISSUE TITLE
dreame.vacuum.p2041o for Domoticz

### ISSUE THREAD

**Issue by codystoica** [Wessie1991/vacuum-mop-pro-2-plus#2]
Hello!
you can adapt this plugin for Domoticz, I noticed that the phython-miio library has support for this model "dreame.vacuum.p2041o".
I aim to be able to turn on the light bulbs automatically in the room where it is vacuuming at night, this would be possible if it reported the room_id in which it is vacuuming.
I did not find any plugin developed for this model with implementation in Domoticz.

I would be very grateful

**Comment by Wessie1991** [comment]
I'm sorry for my late reaction is was not actively busy with this project, are still needed?

**Comment by codystoica** [comment]
Hello!  I haven't managed to integrate the vacuum cleaner in Domoticz, I would be grateful if you could do that.
That's
